# Generated by Django 4.2.4 on 2023-08-29 14:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('randoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bet',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
